name: Stock Portfolio Updates

on:
  schedule:
    - cron: '0 9 * * *'  # Adjust the schedule as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or whichever version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          # Install any other dependencies your script needs
          # e.g., pip install -r requirements.txt

      - name: Write service account JSON
        run: echo "$SERVICE_ACCOUNT_JSON" > service_account.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Run Python script
        run: python main.py
